### ISSUE TITLE
file:///C:/Users/ITek%20Computer%20Ltd/Desktop/New%20folder/New%20folder/school_web.html/assets/

### ISSUE THREAD

**Issue by aline-precious** [HabinezaCedrick/apape#1]
@habinezacedrick
@aline-precious
[Uploading school_web…]()

**Comment by aline-precious** [comment]
just mfasha umbwire ko wayibonye github yambereye intambara

**Comment by aline-precious** [comment]
#habinezacedrick

**Comment by HabinezaCedrick** [comment]
on gitHub ntago nabibonye pe gusa whatsapp yo byaje

**Comment by aline-precious** [comment]
hi
long time ,how is things going there ?
just its a long story mbona nzakubwira
nuburyo administration staff yabyinjiyemo
bigapha .but umeze ute

**Comment by HabinezaCedrick** [comment]
I am fine at all sisiter
Actually no problem for what happened
Gusa meze neza cyane kandi
Courage wowe ntuzacike intege mwana
On Mon, 15 Nov 2021 at 21:03, aline-precious ***@***.***>
wrote:time ,how is things going there ?

**Comment by aline-precious** [comment]
hi
how have you been doing in this days ?
for me am at school with many tasks and exams
how are you doing out there ?
from aline

**Comment by HabinezaCedrick** [comment]
I am doing good and I wish you all the best in your exams actually good
luck
